name: Daily Surf Report

on:
  # Schedule the workflow to run daily at 20:00 UTC
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    environment: production
    steps:
      - name: Install Git in Alpine Container (Before Checkout)
        run: |
          apk update
          apk add --no-cache git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies, Chromium, and Chromedriver (Alpine Container - Continued)
        run: |
          # Git is already installed in the previous step
          apk add --no-cache python3 py3-pip chromium chromium-chromedriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Chromium version:"
          chromium --version || echo "Chromium command not found"
          echo "Chromedriver version:"
          chromedriver --version || echo "Chromedriver command not found in PATH"

      - name: Run script
        run: |
          python -m sources.beachbot.main 2>&1 | tee run.log
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          STATION_NUMBER: ${{ secrets.STATION_NUMBER }}
          SMTPSERVER: ${{ secrets.SMTPSERVER }}
          SMTPORT: ${{ secrets.SMTPORT }}
          SENDEREMAIL: ${{ secrets.SENDEREMAIL }}
          RECEIVEREMAIL: ${{ secrets.RECEIVEREMAIL }}
          EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
          browser: ${{ secrets.browser }}

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-logs
          path: run.log