name: Daily Surf Report
environment: production
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python Venv and Install Dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          echo "Station number from secrets: $STATION_NUMBER"
          . .venv/bin/activate
          python -m sources.beachbot.main
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          STATION_NUMBER: ${{ secrets.STATION_NUMBER }}
          SMTPSERVER: ${{ secrets.SMTPSERVER }}
          SMTPORT: ${{ secrets.SMTPPORT }}
          SENDEREMAIL: ${{ secrets.SENDEREMAIL }}
          RECEIVEREMAIL: ${{ secrets.RECEIVEREMAIL }}
          EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
          browser: ${{ secrets.browser }}

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-logs
          path: run.log
