jobs:
  build_and_run:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest

    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python Venv and Install Dependencies
        run: |
          python3 -m venv .venv && \
          . .venv/bin/activate && \
          pip install --upgrade pip && \
          pip install -r requirements.txt

          echo "Chrome version in container:"
          google-chrome --version || chromium --version || echo "Chrome/Chromium not found"
          echo "Chromedriver version in container:"
          chromedriver --version || echo "Chromedriver not found"

      - name: Run script
        run: |
          . .venv/bin/activate
          python -m sources.beachbot.main 2>&1 | tee run.log
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          STATION_NUMBER: ${{ secrets.STATION_NUMBER }}
          SMTPSERVER: ${{ secrets.SMTPSERVER }}
          SMTPORT: ${{ secrets.SMTPORT }}
          SENDEREMAIL: ${{ secrets.SENDEREMAIL }}
          RECEIVEREMAIL: ${{ secrets.RECEIVEREMAIL }}
          EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
          browser: ${{ secrets.browser }}

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-logs
          path: run.log